### ISSUE TITLE
Error in auth

### ISSUE THREAD

**Issue by tatyanavolkova** [michaelkrukov/vk-group-wall-prober#1]
Hello! 

I get the following error:

{'error': {'error_code': 5, 'error_msg': 'User authorization failed: method is unavailable with group auth.', 'request_params': [{'key': 'oauth', 'value': '1'}, {'key': 'method', 'value': 'wall.get'}, {'key': 'v', 'value': '5.74'}, {'key': 'owner_id', 'value': '-165420069'}, {'key': 'count', 'value': '100'}]}}

What am I doing wrong? I successfully post to my group using the same credentials (token + id)

**Comment by michaelkryukov** [comment]
Method "wall.get" which is used in this script is only callable for users, not for groups.
